"""empty message

Revision ID: b4c32f19b043
Revises: 779d3f3d2085
Create Date: 2022-10-02 21:49:57.898311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c32f19b043'
down_revision = '779d3f3d2085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=15), nullable=False),
    sa.Column('eye_color', sa.String(length=25), nullable=False),
    sa.Column('skin_color', sa.String(length=25), nullable=False),
    sa.Column('height', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
