"""empty message

Revision ID: d2cbdba16124
Revises: c64a18fa997f
Create Date: 2022-10-01 21:53:49.286482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cbdba16124'
down_revision = 'c64a18fa997f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('population', sa.String(length=50), nullable=False),
    sa.Column('terrain', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('first_name', sa.String(length=15), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_table('planets')
    # ### end Alembic commands ###
